### ISSUE TITLE
Loading a loadout, editing it, then reloading it does not properly reset action counts 

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [dmchurch/omsi-loops#11]
**Describe the bug**
If you load a loadout, start editing it, and then decide you don't like the changes you made, the natural way to revert them is to load the loadout again without saving it. However, doing this does not properly load action counts.

**To Reproduce**
1. Load a loadout using the "Manage Loadouts" button.
2. Change the number of times that any action is performed
3. Add any action to the list.
4. Without saving it, reload the same loadout using the "Manage Loadouts" button.
5. See that the action changed in step 2 still has the new number.

**Expected behavior**
Upon reloading the loadout in step 4, I expected the number changed in step 2 to be reverted to how it was when the loadout was last saved.

**Screenshots**
https://github.com/user-attachments/assets/ef0a32d5-e512-441a-8e4a-682a43b7014e

**Savefile**
N/A

**Additional context**

**Comment by Mojken** [comment]
This is still an issue. Any thoughts on fixing it @dmchurch?

**Comment by dmchurch** [comment]
Thanks for the ping, @Mojken, I hadn't seen this! I'll take a look in the morning.

**Comment by dmchurch** [comment]
Go ahead and refresh the page when you have a chance, @Mojken, this should be resolved! (reminder that on some browsers you may need to hard-refresh to get the script updates; ctrl-shift-R or cmd-shift-R will usually do the trick)
